# Author : Mborne

services:
    s3_client:
        class: 'AsyncAws\S3\S3Client'
        arguments:
            -  endpoint: '%env(S3_ENDPOINT)%'
               accessKeyId: '%env(S3_ACCESS_KEY)%'
               accessKeySecret: '%env(S3_SECRET_KEY)%'
               region: '%env(S3_REGION)%'
               # required for minio (avoids access to {bucket}.minio-s3.dev.localhost)
               pathStyleEndpoint: true

flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/data'
        data.storage:
            adapter: 'asyncaws'
            options:
                client: 's3_client'
                bucket: '%env(S3_BUCKET)%'