version: "3"

networks:
  symfony:

volumes:
  db-data:

services:
  backend:
    build:
      context: .
      dockerfile: docker-config/backend.dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "3001-3002:80"
    env_file:
      - .env.local
    networks:
      - symfony
    restart: unless-stopped

  postgres:
    image: postgres:10
    tty: true
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "4000:5432"
    networks:
      - symfony
    restart: unless-stopped

  nginx:
    image: nginx:latest
    env_file:
      - .env.local
    ports:
      - "5000:80"
    volumes:
      - ./docker-config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - symfony
    restart: unless-stopped
