version: "3"

networks:
  symfony:

volumes:
  db-data:

services:
  backend:
    build:
      context: .
      dockerfile: docker-config/backend.dockerfile
    container_name: backend
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "3000:80"
    env_file:
      - .env.local
    networks:
      - symfony
    restart: unless-stopped

  postgres:
    image: postgres:10
    container_name: postgres
    tty: true
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "4000:5432"
    networks:
      - symfony
    restart: unless-stopped
