version: "3"

networks:
  symfony:

volumes:
  db-data:

services:
  backend:
    build:
      context: .
      dockerfile: .docker/backend.dockerfile
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "3001-3002:80"
    env_file:
      - .env.local
    networks:
      - symfony
    restart: unless-stopped

  postgres:
    image: postgres:10
    tty: true
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "4000:5432"
    networks:
      - symfony
    restart: unless-stopped

  nginx:
    image: nginx:latest
    env_file:
      - .env.local
    ports:
      - "5000:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - symfony
    restart: unless-stopped
    depends_on:
      - backend

  scheduler:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/scheduler-config.ini:/etc/ofelia/config.ini
    depends_on:
      - backend
