# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3

    steps:
      - checkout

      - run:
          name: Creating .env.test
          command: ./create-env-test.sh
      - run:
          name: Log in to docker
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Launching docker containers
          command: docker-compose -f ./../docker-compose.test.yml up -d --build --remove-orphans
      - run:
          name: Updating PHP dependencies
          command: docker exec -it validator-api_backend_test_1 composer update --no-interaction
      - run:
          name: Creating database (if doesn't exist already)
          command: docker exec -it validator-api_backend_test_1 php bin/console --env=test doctrine:database:create --if-not-exists
      - run:
          name: Migrating database schema
          command: docker exec -it validator-api_backend_test_1 php bin/console --env=test doctrine:migrations:migrate --no-interaction
      - run:
          name: Running check on validator-cli.jar's arguments
          command: docker exec -it validator-api_backend_test_1 php bin/console --env=test app:args-config-check
      - run:
          name: Downloading a prespecified version of validator-cli.jar
          command: docker exec -it validator-api_backend_test_1 ./download-validator.sh 4.0.4
      - run:
          name: Running phpunit tests
          command: docker exec -it validator-api_backend_test_1 vendor/bin/simple-phpunit
