# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02

    steps:
      - checkout

      - run:
          name: Log in to docker
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build docker image for the api
          command: docker-compose build api
      - run:
          name: Run phpunit tests
          command: docker-compose run --rm api .docker/application.sh test
      - run:
          name: Export tests results to output.tgz
          command: docker run --rm -v project_api-data:/data busybox sh -c 'tar -cOzf - /data/output' > output.tgz
      - run:
          name: Extract output.tgz
          command: mkdir -p var && tar -xvzf output.tgz -C var
      - store_test_results:
          path: var/data/output
      - store_artifacts:
          path: var/data/output/coverage

general:
  branches:
    only:
      - master
      - develop
