services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $validationsDir: "%env(resolve:DATA_DIR)%/validations-test"
      $projectDir: "%kernel.project_dir%"
      $validatorPath: "%ignf_validator.path%"
      $validatorJavaOpts: "%env(resolve:VALIDATOR_JAVA_OPTS)%"
      $gmlasConfigPath: "%env(resolve:GMLAS_CONFIG)%"

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Storage\ValidationsStorage:
    public: true
