services:
  _defaults:
    bind:
      $validationsDir: "%env(resolve:DATA_DIR)%/validations-test"

  App\Storage\ValidationsStorage:
    public: true

  App\Tests\DataFixtures\:
    resource: "../tests/DataFixtures"
