openapi: "3.0.0"

info:
  description: >
    APIsation de l'outil [Validator](https://github.com/IGNF/validator), outil permettant de valider et normaliser les données présentes dans une arborescence de fichiers.

  version: "1.0.0"
  title: "API Validator"
  termsOfService: "" # TODO
  contacts:
    email: "loremipsum@ign.fr" # TODO
  license:
    name: "CECILL-B" # TODO
    url: "http://www.cecill.info/licences/Licence_CeCILL-B_V1-fr.html"
host: "https://api.ign.fr/validator-api"
servers:
  - url: https://api.ign.fr/validator-api
basePath: "v1"
tags:
  - name: "validation"
    description: "Une demande de validation de documents"
schemes:
  - "https"
paths:
  /validator/validations/:
    post:
      tags:
        - validation
      operationId: upload_dataset
      summary: "Téléverser un jeu de données à faire valider"
      description: "Téléverser un jeu de données sur le serveur afin demander une validation plus tard"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                dataset:
                  type: string
                  format: binary
      responses:
        201:
          description: "Téléversement réussi"
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                    example: g7258vq1t639uagbv8rg7b97
                  dataset_name:
                    type: string
                    example: 130010853_PM3_60_20180516
                  arguments:
                    type: json
                    example: null
                  date_creation:
                    type: datetime
                    example: "2020-10-14T17:46:54+02:00"
                  status:
                    type: string
                    example: waiting_for_args
                  message:
                    type: string
                    example: null
                  date_start:
                    type: datetime
                    example: null
                  date_finish:
                    type: datetime
                    example: null
                  results:
                    type: string
                    example: null
        400:
          description: Jeu de données (dans un fichier compressé .zip) manquant ou autre type de fichier a été fourni
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
  /validator/validations/{uid}:
    get:
      tags:
        - validation
      operationId: get_validation
      summary: "Voir une validation"
      description: "Voir les détails d'une demande de validation"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      responses:
        200:
          description: Récupération réussie
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
        400:
          description: "Paramètre uid manquant"
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
        404:
          description: "Aucune demande de validation ne correspond à l'uid"
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"

    patch:
      tags:
        - validation
      operationId: update_arguments
      summary: "Préciser les arguments de validator"
      description: "Préciser les arguments et les options pour le programme ligne de commandes Validator"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      requestBody:
        content:
          application/json:
            schema:
              properties:
                arguments:
                  type: string
                  description: les arguments du programme ligne de commandes Validator sous forme d'une chaîne de caractères
                  required: true
                  example: "-s EPSG:2154 -m https://ocruze.github.io/fileserver/config/cnig_CC_2017.json"
      responses:
        200:
          description: "Mise à jour réussie"
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                    example: g7258vq1t639uagbv8rg7b97
                  dataset_name:
                    type: string
                    example: 130010853_PM3_60_20180516
                  arguments:
                    type: json
                    example:
                      {
                        "s": "EPSG:2154",
                        "m": "http://localhost/config/cnig_SUP_PM3_2016.json",
                      }
                  date_creation:
                    type: datetime
                    example: "2020-10-14T17:46:54+02:00"
                  status:
                    type: string
                    example: pending
                  message:
                    type: string
                    example: null
                  date_start:
                    type: datetime
                    example: null
                  date_finish:
                    type: datetime
                    example: null
                  results:
                    type: string
                    example: null
        400:
          description: Paramètres uid ou arguments manquants, ou certains des arguments fournis ne sont pas autorisés
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
        403:
          description: La validation a été archivée (plus de 30 jours dépassés depuis la création)
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
        404:
          description: Aucune demande de validation ne correspond à l'uid
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"

    delete:
      tags:
        - validation
      operationId: delete_validation
      summary: "Supprimer une validation"
      description: "Demander la suppression de la validation et ses fichiers d'entrée"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      responses:
        204:
          description: "Suppression réussie"
          content: null
        400:
          description: Paramètres uid manquant
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
        404:
          description: Aucune demande de validation ne correspond à l'uid
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"

definitions:
  Error:
    properties:
      code:
        type: integer
        description: code de l'erreur rencontrée
      error:
        type: string
        description: message précis de l'erreur rencontrée
