openapi: "3.0.0"

info:
  description: >
    API permettant d'appeler [IGNF/validator](https://github.com/IGNF/validator) pour valider et normaliser des dossiers contenant une arborescence de fichiers.
  contact:
    name: IGNF/validator
    url: "https://github.com/IGNF/validator/issues"
  version: "0.2.1"
  title: "API Validator"
  license:
    name: "AGPL-3.0-or-later"
    url: "https://www.gnu.org/licenses/agpl-3.0.txt"

tags:
  - name: "validation"
    description: "Une demande de validation de documents"

paths:
  /api/validations/:
    post:
      tags:
        - validation
      operationId: upload_dataset
      summary: "Téléverser un jeu de données à faire valider"
      description: "Téléverser un jeu de données sur le serveur afin demander une validation plus tard"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                dataset:
                  type: string
                  format: binary
      responses:
        201:
          description: "Téléversement réussi"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Validation"
        400:
          description: Jeu de données (dans un fichier compressé .zip) manquant ou autre type de fichier a été fourni
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/validations/{uid}:
    get:
      tags:
        - validation
      operationId: get_validation
      summary: "Voir une validation"
      description: "Voir les détails d'une demande de validation"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      responses:
        200:
          description: Récupération réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Validation"
        400:
          description: "Paramètre uid manquant"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "Aucune demande de validation ne correspond à l'uid"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      tags:
        - validation
      operationId: update_arguments
      summary: "Préciser les arguments de validator"
      description: "Préciser les arguments et les options pour le programme ligne de commandes Validator"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ValArgs"
      responses:
        200:
          description: "Mise à jour réussie"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Validation"
        400:
          description: Paramètres uid ou arguments manquants, ou certains des arguments fournis ne sont pas autorisés
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        403:
          description: La validation a été archivée (plus de 30 jours dépassés depuis la création)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Aucune demande de validation ne correspond à l'uid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      tags:
        - validation
      operationId: delete_validation
      summary: "Supprimer une validation"
      description: "Demander la suppression de la validation et tous les fichiers qui lui sont associés"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      responses:
        204:
          description: "Suppression réussie"
        400:
          description: Paramètres uid manquant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Aucune demande de validation ne correspond à l'uid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"



  /api/validations/{uid}/results.csv:
    get:
      tags:
        - validation
      operationId: get_validation_csv
      summary: "Télécharger le résultat au format CSV"
      description: "Télécharger le résultat au format CSV"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      responses:
        200:
          description: Récupération réussie
          content:
            text/csv: {}
        400:
          description: "Paramètre uid manquant"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "Aucune demande de validation ne correspond à l'uid"
          content:

            application/json:
              schema:
                $ref: "#/components/schemas/Error"


  /api/validations/{uid}/files/source:
    get:
      tags:
        - validation
      summary: "Télécharger les données de source"
      description: "Télécharger les données de source dans un fichier compressé (zip) et nommé {nom_dataset}-source.zip"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      responses:
        200:
          description: "Contenu téléchargeable trouvé"
          content:
            application/zip:
              schema:
                format: binary
        403:
          description: Aucun contenu téléchargeable trouvé parce que la validation a été archivée (plus de 30 jours sont passés depuis la création)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Aucune demande de validation ne correspond à l'uid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/validations/{uid}/files/normalized:
    get:
      tags:
        - validation
      summary: "Télécharger les données normalisées"
      description: "Télécharger les données normalisées générées par le validateur dans un fichier compressé (zip) nommé {nom_dataset}-normalized.zip"
      parameters:
        - description: "Identifiant unique de la validation"
          in: path
          name: uid
          required: true
          schema:
            type: string
          example: g7258vq1t639uagbv8rg7b97
      responses:
        200:
          description: "Contenu téléchargeable trouvé"
          content:
            application/zip:
              schema:
                format: binary
        403:
          description: Aucun contenu téléchargeable trouvé parce que soit la validation n'a pas encore été exécutée, elle a été archivée (plus de 30 jours dépassés depuis la création), ou bien elle a terminé en une erreur
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Aucune demande de validation ne correspond à l'uid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:

    Validation:
      description: "Une validation avec ses informations et ses résultats"
      type: object
      properties:
        uid:
          type: string
          example: g7258vq1t639uagbv8rg7b97
        status:
          type: string
          enum:
            - waiting_for_args
            - pending
            - processing
            - finished
            - error
            - archived
          example: waiting_for_args
        dataset_name:
          type: string
          example: 130010853_PM3_60_20180516
        arguments:
          type: object
          example: null
        date_creation:
          type: string
          example: "2020-10-14T17:46:54+02:00"
        message:
          type: string
          example: null
        date_start:
          type: string
          example: null
        date_finish:
          type: string
          example: null
        results:
          type: string
          example: null

    Error:
      type: object
      properties:
        code:
          type: integer
          description: code de l'erreur rencontrée
        error:
          type: string
          description: message précis de l'erreur rencontrée

    ValArgs:
       $ref: "./schema/validator-arguments.json"
