name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env: 
          DATABASE_URL: postgresql://postgres:postgres@validator-api_postgres_1:4000/validator-api?serverVersion=10&charset=utf8
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: validator-api
          
      - name: create .env.test file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: $DATABASE_URL
          envkey_POSTGRES_USER: $POSTGRES_USER
          envkey_POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          envkey_POSTGRES_DB: $POSTGRES_DB
          file_name: .env.test
          
      - name: launch docker containers
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: install dependencies
        run: docker exec validator-api_backend_test_1 composer update
        
      - name: create db
        run: docker exec validator-api_backend_test_1 php bin/console --env=test doctrine:database:create --if-not-exists
          
      - name: update db schema
        run: docker exec validator-api_backend_test_1 php bin/console --env=test doctrine:migrations:migrate --no-interaction
        
      - name: fetch validator-cli.jar
        run: docker exec validator-api_backend_test_1 ./download-validator.sh 4.0.4

      - name: launch tests
        run: docker exec validator-api_backend_test_1 vendor/bin/simple-phpunit
