name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: create .env.test file
        run: |
          touch .env.test
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/validator-api?serverVersion=10&charset=utf8" >> .env.test
          echo "POSTGRES_USER=postgres" >> .env.test
          echo "POSTGRES_PASSWORD=postgres" >> .env.test
          echo "POSTGRES_DB=validator-api" >> .env.test
          cat .env.test
          
      - name: launch docker containers
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: install dependencies
        run: docker exec validator-api_backend_test_1 composer update
        
      - name: create db
        run: docker exec validator-api_backend_test_1 php bin/console --env=test doctrine:database:create --if-not-exists
          
      - name: update db schema
        run: docker exec validator-api_backend_test_1 php bin/console --env=test doctrine:migrations:migrate --no-interaction
        
      - name: fetch validator-cli.jar
        run: docker exec validator-api_backend_test_1 ./download-validator.sh 4.0.4

      - name: launch tests
        run: docker exec validator-api_backend_test_1 vendor/bin/simple-phpunit
